language: php
sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

before_install:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/security-core:$SYMFONY_VERSION symfony/config:$SYMFONY_VERSION symfony/http-foundation:$SYMFONY_VERSION symfony/dependency-injection:$SYMFONY_VERSION symfony/http-kernel:$SYMFONY_VERSION; fi

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
    - vendor/bin/phpspec run -fpretty --verbose

jobs:
    include:
        # Tests the lowest set of dependencies
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-lowest"

        # Test against latest Symfony 4.4
        - php: 7.3
          env: SYMFONY_VERSION="4.4.*"

        # Test against latest Symfony 5.0
        - php: 7.3
          env: SYMFONY_VERSION="5.0.*"

        - stage: "Code style analysis"
          php: 7.3
          env: SYMFONY_VERSION=""
          script:
              - vendor/bin/ecs check src spec --no-progress-bar

        - stage: "Static Analysis"
          php: 7.3
          env: SYMFONY_VERSION=""
          script:
              - vendor/bin/phpstan analyse
