language: php

sudo: false

stages:
    - Code style analysis
    - Static Analysis
    - test

php:
    - 7.1
    - 7.2
    - 7.3

env:
    matrix:
        - SYMFONY_VERSION=^3.0
        - SYMFONY_VERSION=^4.0

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - composer self-update
    - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/security:$SYMFONY_VERSION symfony/config:$SYMFONY_VERSION symfony/http-foundation:$SYMFONY_VERSION symfony/dependency-injection:$SYMFONY_VERSION symfony/http-kernel:$SYMFONY_VERSION; fi

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
    - vendor/bin/phpspec run -fpretty --verbose

jobs:
    include:
        - stage: "Code style analysis"
          php: 7.3
          env: SYMFONY_VERSION=""
          script:
              - vendor/bin/php-cs-fixer fix --dry-run -v --show-progress=dots --diff-format=udiff
        - stage: "Static Analysis"
          php: 7.3
          env: SYMFONY_VERSION=""
          script:
              - vendor/bin/phpstan analyse
