services:
    _defaults:
        autowire: true
        public: false
        autoconfigure: true

    TheRedDot\MonologExtraBundle\:
        resource: '../../{Logger,EventListener,Processor,Provider}'
